config/routes.rb
Rails.application.routes.draw do
  resources :users
  root :to => 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: "12345678"
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)
    # @user.upload_filename = @user[:upload_file].original_filename
    # @user.upload_file = @user[:file].read

    # @user.save
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Upload success'}
        format.json { render :show, status: :created, location: @user }
      else
        @users = User.all
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Upload success' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Upload success' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # binding.pry
      params.require(:user).permit(:name, :upload_file, :upload_filename)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-logo">
        <a href="/users">トップ</a>
      </div>
      <ul class="header-menus">
        <li>
          <a href="/users/new">あーー</a>
        </li>
      </ul>
    </header>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div id="upload_area" class="drop_field">
    <%= form.label :upload_file, "開発データ" %>
    <div id="drop_area">
      <%= form.file_field :upload_file %>
    </div>
    <div id="drop_area">
      <%= form.file_field :upload_file %>
    </div>
  </div>

  <div class="field">
    <%= form.label :name, '名前' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Upload" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="main top-main">
  <div class="top-message">
      <p>さーばーせんたく</p>
  </div>
</div>

app/views/users/new.html.erb
<div class="main posts-new">
  <div class="container">
    <%= render 'form', user: @user %>
  </div>
</div>
<!-- <%= link_to 'Back', users_path %> -->

app/views/users/show.html.erb
<div class="main top-main">
  <div class="top-message">
      <p>アップロード完了</p>
  </div>
</div>